In [1]:
import torch

In [7]:
x = torch.FloatTensor([0,0,0,1,2,2])


# Create a mask for elements equal to the top value
mask = torch.eq(x, torch.topk(x,k=1).values[0])

# Get the indices where the mask is True
indices_of_top_values = torch.nonzero(mask).squeeze()
print(indices_of_top_values)

tensor([4, 5])


In [68]:

# Get the top k values and indices
k = 4
top_values, top_indices = torch.topk(x, k)

# Create a mask for elements equal to the top value
print(top_values)
mask = torch.eq(x, top_values[k-1])

# Get the indices where the mask is True
indices_of_top_values = torch.nonzero(mask).squeeze()

# Randomly pick one index
if indices_of_top_values.shape:
    random_index = torch.multinomial(torch.ones_like(indices_of_top_values, dtype=torch.float32), 1).item()
    
    selected_index = indices_of_top_values[random_index]
else:
    selected_index = indices_of_top_values
print("Top value:", top_values[0].item())
print("Indices of top values:", indices_of_top_values.tolist())
print("Randomly selected index:", selected_index.item())

tensor([2., 2., 1., 0.])
Top value: 2.0
Indices of top values: [0, 1, 2]
Randomly selected index: 2


In [314]:
y = torch.FloatTensor([[0,0,0,1,2,2],[2,2,4,5,7,8]])

In [512]:
y = torch.FloatTensor([[0,0,0,1,2,2],[2,2,4,5,7,8]])
k = 1
top_values, top_indices = torch.topk(y, k,dim=1)
print(top_indices)

tensor([[4],
        [5]])


In [540]:
# Generate a random permutation of column indices
permuted_indices = torch.randperm(y.shape[1])

# Permute the columns of the matrix
permuted_matrix = y[:, permuted_indices]

print("Original Matrix:\n", y)
print("Permuted Matrix:\n", permuted_matrix)
print("Permutation Mapping:\n", permuted_indices)

Original Matrix:
 tensor([[0., 0., 0., 1., 2., 2.],
        [2., 2., 4., 5., 7., 8.]])
Permuted Matrix:
 tensor([[1., 2., 0., 0., 2., 0.],
        [5., 7., 2., 4., 8., 2.]])
Permutation Mapping:
 tensor([3, 4, 1, 2, 5, 0])


In [865]:
# This can be done once
permuted_indices = torch.stack([torch.randperm(y.shape[1]) for _ in range(y.shape[0])])
# Permute the columns of the matrix
permuted_matrix = torch.gather(y,1,permuted_indices)

print("Original Matrix:\n", y)
print("Permuted Matrix:\n", permuted_matrix)
print("Permutation Mapping:\n", permuted_indices)



# Invert the permutation
inverse_permuted_indices = torch.argsort(permuted_indices)
print("Inverse Mapping:\n", inverse_permuted_indices)
print("Original After Inversion:\n", torch.gather(permuted_matrix,1,inverse_permuted_indices))

k = 2
top_values, top_indices = torch.topk(permuted_matrix,k)
print("Top Values:\n", top_values)
print("All Top Indices:\n", top_indices,top_indices.shape)
top_indices = top_indices[:,k-1:k]
print("Top Indices:\n", top_indices,top_indices.shape)

print("Original Top:\n", torch.gather(permuted_indices,1,top_indices))
# print("Original Top:\n", permuted_indices[:,top_indices])

Original Matrix:
 tensor([[0., 0., 0., 1., 2., 2.],
        [2., 2., 4., 5., 7., 8.]])
Permuted Matrix:
 tensor([[0., 2., 0., 0., 2., 1.],
        [4., 2., 5., 7., 8., 2.]])
Permutation Mapping:
 tensor([[0, 4, 1, 2, 5, 3],
        [2, 1, 3, 4, 5, 0]])
Inverse Mapping:
 tensor([[0, 2, 3, 5, 1, 4],
        [5, 1, 0, 2, 3, 4]])
Original After Inversion:
 tensor([[0., 0., 0., 1., 2., 2.],
        [2., 2., 4., 5., 7., 8.]])
Top Values:
 tensor([[2., 2.],
        [8., 7.]])
All Top Indices:
 tensor([[1, 4],
        [4, 3]]) torch.Size([2, 2])
Top Indices:
 tensor([[4],
        [3]]) torch.Size([2, 1])
Original Top:
 tensor([[5],
        [4]])


In [1010]:
# This can be done once
permuted_indices = torch.stack([torch.randperm(y.shape[1]) for _ in range(y.shape[0])])
# Permute the columns of the matrix
permuted_matrix = torch.gather(y,1,permuted_indices)

print("Original Matrix:\n", y)
print("Permuted Matrix:\n", permuted_matrix)
print("Permutation Mapping:\n", permuted_indices)



# Invert the permutation
inverse_permuted_indices = torch.argsort(permuted_indices)
print("Inverse Mapping:\n", inverse_permuted_indices)
print("Original After Inversion:\n", torch.gather(permuted_matrix,1,inverse_permuted_indices))

k = 4
top_values, top_indices = torch.topk(permuted_matrix,k)
print("Top Values:\n", top_values)
print("All Top Indices:\n", top_indices,top_indices.shape)
# top_indices = top_indices[:,k-1:k]
# print("Top Indices:\n", top_indices,top_indices.shape)

# print("Original Top:\n", torch.gather(permuted_indices,1,top_indices),torch.gather(permuted_indices,1,top_indices).shape)


top_indices = top_indices[:,k-1]
print("Top Indices:\n", top_indices,top_indices.shape)

ot =  permuted_indices[torch.arange(permuted_indices.size(0)), top_indices]
print("Original Top:\n", ot,ot.shape)

# print("Original Top:\n", permuted_indices[:,top_indices])

Original Matrix:
 tensor([[0., 0., 0., 1., 2., 2.],
        [2., 2., 4., 5., 7., 8.]])
Permuted Matrix:
 tensor([[2., 0., 0., 1., 2., 0.],
        [2., 2., 4., 5., 8., 7.]])
Permutation Mapping:
 tensor([[5, 1, 2, 3, 4, 0],
        [1, 0, 2, 3, 5, 4]])
Inverse Mapping:
 tensor([[5, 1, 2, 3, 4, 0],
        [1, 0, 2, 3, 5, 4]])
Original After Inversion:
 tensor([[0., 0., 0., 1., 2., 2.],
        [2., 2., 4., 5., 7., 8.]])
Top Values:
 tensor([[2., 2., 1., 0.],
        [8., 7., 5., 4.]])
All Top Indices:
 tensor([[0, 4, 3, 2],
        [4, 5, 3, 2]]) torch.Size([2, 4])
Top Indices:
 tensor([2, 2]) torch.Size([2])
Original Top:
 tensor([2, 2]) torch.Size([2])


In [576]:
# Generate a random permutation of column indices for all rows
permuted_indices = torch.stack([torch.randperm(y.shape[0]) for _ in range(y.shape[1])])

# Create a tensor of row indices for indexing along rows
row_indices = torch.arange(y.shape[1]).view(-1, 1)

# Use the indices to permute the columns of the matrix
print(row_indices)
print(permuted_indices)
permuted_matrix = y[row_indices, permuted_indices]

print("Original Matrix:\n", matrix)
print("Permuted Matrix:\n", permuted_matrix)
print("Permutation Mapping:\n", permuted_indices)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])
tensor([[1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1]])


IndexError: index 2 is out of bounds for dimension 0 with size 2

In [147]:
# Get the top k values and indices
top_values, top_indices = torch.topk(y, k,dim=1)

# Create a mask for elements equal to the top value
mask = torch.eq(y, top_values)

# Get the indices where the mask is True
indices_of_top_values = torch.nonzero(mask)

reshaped_indices = indices_of_top_values.view(k, -1, indices_of_top_values.shape[-1])
random_indices = torch.multinomial(torch.ones_like(reshaped_indices[:, 0, 0], dtype=torch.float32), 1)
print(indices_of_top_values)

# Gather the randomly selected indices
selected_indices = torch.gather(reshaped_indices, 1, random_indices.view(-1, 1, 1))

# Squeeze the selected_indices tensor to remove any singleton dimensions
selected_indices = selected_indices.squeeze(1)

print("Top values:\n", top_values)
print("Indices of top values:\n", indices_of_top_values)
print("Randomly selected indices:\n", selected_indices)



tensor([[0, 4],
        [0, 5],
        [1, 5]])
Top values:
 tensor([[2.],
        [8.]])
Indices of top values:
 tensor([[0, 4],
        [0, 5],
        [1, 5]])
Randomly selected indices:
 tensor([[0]])


In [313]:
# Get the top n values and indices
k = 1
top_values, top_indices = torch.topk(y, k=1,dim=1)

# Create a mask for elements equal to the top value
mask = torch.eq(y, top_values)

# Get the indices where the mask is True
top_indices = torch.nonzero(mask)

# Get unique values in the first column
unique_values, inverse_indices = torch.unique(top_indices[:, 0], return_inverse=True)

print("U",unique_values)
print("I",inverse_indices)
# Randomly select one row for each unique value
random_indices = torch.randint(0, torch.max(torch.bincount(inverse_indices)), (1,))
print(random_indices)

# Use the random indices to select rows
result_tensor = top_indices[inverse_indices == unique_values[random_indices]]

print("Original Tensor:\n", top_indices)
print("Selected Rows:\n", result_tensor)

U tensor([0, 1])
I tensor([0, 0, 1])
tensor([0])
Original Tensor:
 tensor([[0, 4],
        [0, 5],
        [1, 5]])
Selected Rows:
 tensor([[0, 4],
        [0, 5]])


In [ ]:
# selected_indices = torch.gather(reshaped_indices, 2, random_indices.unsqueeze(2))

# # Squeeze the selected_indices tensor to remove any singleton dimensions
# selected_indices = selected_indices.squeeze(2)

# print("Top values:\n", top_values)
# print("Indices of top values:\n", indices_of_top_values)
# print("Randomly selected indices:\n", selected_indices)


# # Randomly pick one index for each row
# random_indices = torch.multinomial(torch.ones_like(reshaped_indices[:, 0], dtype=torch.float32), 1)

# # Gather the randomly selected indices
# selected_indices = torch.gather(reshaped_indices, 1, random_indices.view(-1, 1))

# print("Top values:\n", top_values)
# print("Indices of top values:\n", indices_of_top_values)
# print("Randomly selected indices:\n", selected_indices)


In [408]:
N, M, K = 1, 2, 3
x = torch.arange(N*M*K).view(N, M, K)
print(x)

# shuffle
idx = torch.randperm(x.size(2))
print(idx)
y = x[..., idx]
print(y)

# reverse the shuffling
idx_inv = torch.sort(idx).indices
print(y[:, idx_inv])

tensor([[[0, 1, 2],
         [3, 4, 5]]])
tensor([2, 1, 0])
tensor([[[2, 1, 0],
         [5, 4, 3]]])


IndexError: index 2 is out of bounds for dimension 0 with size 2